version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/mash-up-dev-recruit-fe
    overwrite: yes

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: codedeploy/after-install.sh
      timeout: 600
      runas: ubuntu
