name: dev-recruit prebuild

on:
  pull_request:
    branches:
      - qa/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Generate Environment Variables File
        run: |
          echo "ANALYZE=$ANALYZE" >> .env.local
          echo "BASE_URL=$BASE_URL" >> .env.local
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.local
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env.local
          echo "GOOGLE_ID=$GOOGLE_ID" >> .env.local
          echo "GOOGLE_SECRET=$GOOGLE_SECRET" >> .env.local
          echo "DESTINATION_URL=$DESTINATION_URL" >> .env.local
          echo "SOURCE_PATH=$SOURCE_PATH" >> .env.local
          echo "NEXT_PUBLIC_CHANNEL_PLUGIN=$NEXT_PUBLIC_CHANNEL_PLUGIN" >> .env.local
          echo "NEXT_PUBLIC_GOOGLE_ANALYTICS=$NEXT_PUBLIC_GOOGLE_ANALYTICS" >> .env.local
        env:
          ANALYZE: ${{ secrets.ANALYZE }}
          BASE_URL: ${{ secrets.BASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          DESTINATION_URL: ${{ secrets.DESTINATION_URL }}
          SOURCE_PATH: ${{ secrets.SOURCE_PATH }}
          NEXT_PUBLIC_CHANNEL_PLUGIN: ${{ secrets.NEXT_PUBLIC_CHANNEL_PLUGIN }}
          NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}

      - name: Install dependencies
        run: yarn install

      - name: build next app
        run: yarn build
